// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package provider

import (
	"github.com/xh-polaris/psych-digital/biz/application/service"
	"github.com/xh-polaris/psych-digital/biz/infrastructure/config"
	"github.com/xh-polaris/psych-digital/biz/infrastructure/mapper/history"
)

// Injectors from wire.go:

func NewProvider() (*Provider, error) {
	configConfig, err := config.NewConfig()
	if err != nil {
		return nil, err
	}
	mongoMapper := history.NewMongoMapper(configConfig)
	historyService := service.HistoryService{
		HistoryMapper: mongoMapper,
	}
	providerProvider := &Provider{
		Config:         configConfig,
		HistoryService: historyService,
	}
	return providerProvider, nil
}
